const profileConstants = {
  LANGUAGES: ['FINNISH', 'ENGLISH', 'SWEDISH'],
  CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR:
    'CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR',
};

export default profileConstants;
